import { Inter } from "next/font/google";
import "./globals.css";
import AppNavbar from '@/app/(Components)/appnavbar/AppNavbar';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
<AppNavbar/>
      {children}
  

      </body>
    </html>
  );
}
